id: T0106
type: Technique

tactic: Reconnaissance

realm: 
  - CI/CDPosture
  - CloudSecurity

summary: Scan configuration on public resources

description: |
  This technique involves scanning the configuration of public cloud resources and CI/CD pipelines for misconfigurations and vulnerabilities that can be exploited by attackers to gain unauthorized access or cause system disruption.
  An attacker can use this technique to identify configuration weaknesses in an organization's cloud infrastructure and CI/CD pipelines, including weak authentication mechanisms, misconfigured security groups, and unsecured storage buckets. 
  By scanning the configuration of public resources, an attacker can develop an understanding of the target's attack surface and identify vulnerabilities that can be exploited in future attacks.

mitigations: 
  - M1550

detections: 
  - D1510

references: 
  - https://www.scmagazine.com/resource/cloud-security/5-challenges-to-public-cloud-security

metadata: 
    version: 0.1
    state: draft

  