id: T0176
type: Technique

tactic: Defense Evasion

realm: 
  - Cloud Security

summary: Misconfigured security measures

description: |
  Misconfiguration of security measures refers to an attack technique where an attacker takes advantage of misconfigured security settings in cloud environments to evade detection and launch further attacks. 
  This technique is commonly used by attackers to gain unauthorized access to cloud resources, exfiltrate data, or launch other types of attacks.
  In cloud environments, misconfigured security measures can occur due to various reasons such as incomplete security configurations, outdated software, or a lack of security controls. 
  Attackers can exploit these misconfigurations to gain access to sensitive information, resources, or systems. 
  For example, an attacker can take advantage of misconfigured security groups or firewall rules to bypass security controls and access sensitive data or resources.

mitigations: 
  - M1530
  - M1550
  - M1720
  - M1760
  - M1761

detections:
  - D1260
  - D1261
  - D1262
  - D1510
  - D1520

subtechinques:
  - T0144
  - T0146

references: 
  - https://www.upguard.com/blog/cloud-misconfiguration

metadata: 
    version: 0.2
    state: draft

  