id: T0189
type: Technique

tactic: Credential Access

realm:
  - SecretsHygiene

summary: Secrets in configuration files

description: |
  It is a very common mistake for developers to keep secrets in configuration files, these can include user crednetials, private keys, api keys etc...  
  Those files are usually the first place where adversaries search for such information.  

mitigations: 
  - M1120
  - M1890

detections: 
  - D1120

references: 
  - https://spectralops.io/blog/where-your-code-secrets-hide-filetypes/

metadata: 
    version: 0.2
    state: draft

  
